### ISSUE TITLE
How to define handlers

### ISSUE THREAD

**Issue by AirBorne04** [bluewings/pug-as-jsx-loader#2]
Hi, i have some troubles figuring out what the suggested syntax for eventhandlers would be?

**was a mixup on my side never mind :) can be closed**

**Comment by bluewings** [comment]
@AirBorne04 
Hi, I've added two examples that use event handlers.
One is simple usage and the other is binding arguments to the handler.

Please let me know if there is a problem.

https://github.com/bluewings/pug-as-jsx-loader/blob/42c4f1eb12b1a504324438114fbdd6dd48ec4954/examples/create-react-app/src/App.pug#L11-L16

**Comment by AirBorne04** [comment]
For me this was not working that way i had to skip the ' and { and just put the plain function reference, but that might be the case due to my specific setup.
