### ISSUE TITLE
codemod.js has some bugs

### ISSUE THREAD

**Issue by seedliu** [bluewings/pug-as-jsx-loader#23]
hi, when i run this loader,  the terminal display error message：

`Module build failed: /Users/xxx/works/React/react-pug/my_app/node_modules/pug-as-jsx-loader/lib/codemod.js:203
      )
      ^
SyntaxError: Unexpected token )`

i find the codemod.js  has many extra commas,  when i clear there commas then webpack run successful.

**Comment by bluewings** [comment]
@seedliu 
It looks like you are using node 7 or lower. I noticed that [trailing-commas-in-function-syntax](https://node.green/#ES2017-features-trailing-commas-in-function-syntax) is not supported in that version.
How about using the latest version of the node (currently 11) or 8 or more?

I will fix the bug you mentioned soon, but it will take some time to publish.

**Comment by seedliu** [comment]
@bluewings 
i use the node 8, it's worked.  thx!

**Comment by bluewings** [comment]
fixed.
