### ISSUE TITLE
[question] How to work with partials/includes?

### ISSUE THREAD

**Issue by douggr** [bluewings/pug-as-jsx-loader#32]
I can't manage to use pug's `include` or `extends`. Is that possible?

Thank you in advance.

**Comment by billypon** [comment]
@douggr You can include/extends directly, but need to do some patch before.

I have created PR, you can do the patch manually: [https://github.com/bluewings/pug-as-jsx-utils/pull/3/files](https://github.com/bluewings/pug-as-jsx-utils/pull/3/files)

**Comment by douggr** [comment]
Many thanks!
