### ISSUE TITLE
Thanks for you work

### ISSUE THREAD

**Issue by jt3k** [bluewings/pug-as-jsx-loader#45]
I have two questions.

1. can i use mixins like [bemto](https://github.com/kizu/bemto)
2. can i use inline styles in a style tag?
![image](https://user-images.githubusercontent.com/1261240/82611455-39e0ff80-9bc9-11ea-9c12-d4142f3a86e9.png)
i also tryied this variants
```pug
style
  .lolo { background: red; }
style
  ='.lolo { background: red; }'
style
  !='.lolo { background: red; }'
style
  |'.lolo { background: red; }'
```

**Comment by bluewings** [comment]
@jt3k 
How about using the `@import CSS` annotation?

If the pug file name is `Sample.pug`, the code below will automatically import `Sample.scss`.
(Definitions for css or scss loaders should be added to webpack.)
```pug
// @import .scss => styles
div(className='{styles.lolo}')
  div(className='{styles.lala}')
    h1 {message}
```

```jsx
import React from 'react';
import styles from './Sample.scss';

export default function (props = {}) {
  const { greetings } = props;
  return (
    { /* @import .scss => styles */ }
    <div className={styles.lolo}>
      <div className={styles.lala}>
        <h1>{message}</h1>
      </div>
    </div>
  );
}
```

**Comment by jt3k** [comment]
👍
