### ISSUE TITLE
possible to use boolean shorthand?

### ISSUE THREAD

**Issue by FicoPrieto** [bluewings/pug-as-jsx-loader#48]
I tried using the boolean shorthand as referenced in the [**Pug**](https://pugjs.org/language/attributes.html#boolean-attributes) and [**React**](https://reacttraining.com/react-router/web/api/NavLink/exact-bool) documentation, but it doesn't seem to work.

For example: `react-router`'s `exact` boolean property only works if I explicitly set it to `{true}`.

### Boolean Is Not Applied
```pug
BrowserRouter
  Nav
  Route(path="/"        component="{Home   }" exact) // 🡸
  Route(path="/about"   component="{About  }"      )
  Route(path="/contact" component="{Contact}"      )
```

### Boolean Is Applied
```pug
BrowserRouter
  Nav
  Route(path="/"        component="{Home   }" exact="{true}") // 🡸
  Route(path="/about"   component="{About  }"               )
  Route(path="/contact" component="{Contact}"               )
```

**Comment by bluewings** [comment]
@FicoPrieto 
I just modified it. Update the module to 1.0.85 to use 'boolean shorthand'.

**Comment by FicoPrieto** [comment]
Awesome, thanks!
