### ISSUE TITLE
support multi template functions

### ISSUE THREAD

**Issue by billypon** [bluewings/pug-as-jsx-loader#49]
Now, this loader will export a default function for template rendering, like this:

```pug
// template.pug
div foo
```

```js
import template from './template.pug';

export default function foo() {
  return template();
}
```

But can we export multi functions? like this:

```pug
// template.pug
block foo
  div bar
```

or

```pug
// template.pug
mixin foo()
  div bar
```

then we can use other functions:

```js
import template from './template.pug';

export default function foo() {
  return template.foo();
}
```

**Comment by billypon** [comment]
[https://github.com/bluewings/pug-as-jsx-utils/pull/14](https://github.com/bluewings/pug-as-jsx-utils/pull/14)

**Comment by bluewings** [comment]
@billypon 
Thanks for a good feature suggestion. I just merged your PR.
And you can use it in 1.0.87.
