### ISSUE TITLE
Replace react-scripts webpack config instead of create-react-app

### ISSUE THREAD

**Issue by SilencerWeb** [bluewings/pug-as-jsx-loader#5]
As I see, when you install pug-as-jsx-loader, it automatically creates webpack configs in the folder named create-react-app.

Before installing pug-as-jsx-loader - http://prntscr.com/haljwb
After - http://prntscr.com/halkc6

But create-react-app uses react-scripts for build project, so, when you run scripts(http://prntscr.com/halkvb) pug-as-jsx-loader doesn't work and you need to go and replace webpack config by yourself.

**Comment by bluewings** [comment]
@SilencerWeb 
I excluded the examples folder from the npm package.
