### ISSUE TITLE
How can I avoid creating *.pug.transpiled files automatically?

### ISSUE THREAD

**Issue by eduardrock** [bluewings/pug-as-jsx-loader#6]
I don't want the files `*.pug.transpiled` to be created automatically. How can I disable it?

@bluewings

**Comment by bluewings** [comment]
You can disable the creation of ```* .pug.transpiled.jsx``` files by adding the ```transfiledFile``` option.

[webpack.config.dev.js](https://github.com/bluewings/pug-as-jsx-loader/blob/master/examples/create-react-app/config/webpack.config.dev.js#L170-L175)
```js
// webpack.config.js
{
  test: /\.pug$/,
  include: paths.appSrc,
  use: [
    require.resolve('babel-loader'),
    {
      loader: require.resolve('pug-as-jsx-loader'),
      options: {
        transpiledFile: false,
      },
    },
  ],
},
```

**Comment by eduardrock** [comment]
@bluewings, but my webpack.config.js file is like this:

```
      {
        test: /\.(pug|js|jsx)$/,
        loaders: ['babel-loader?presets[]=es2015&presets[]=react', 'pug-as-jsx-loader'],
      },
```

In which part do I have to put that code?
